<div id="header" class="contentHolder">
    
    <div class="left">
        <h1>PHP ZF combine<br />with Google API.</h1>
    </div>
    <div class="right">
        <img alt="logo" src="./images/logo-header.png">
        <div id="details">
            <h3>Janjić Miloš</h3>
            <p id="abbrev">i.<br>m.</p>
            <p>11640<br>dr Vidaković Milan</p>
        </div>
    </div>
</div>

<div id="login" class="contentHolder">
    <a href="<?php echo $this->loginUrl; ?>">login here</a>

</div>
<!-- 
<div id="login" class="contentHolder">
    <form action="/home/login" name="login_form" method="POST" id="loginForm"> 
        <div class="textFieldHolder">
            <span>Username*</span><br>
            <input type="text" value="" name="username">
        </div>
        <div class="textFieldHolder">
            <span>Password*</span><br>
            <input type="password" value="" name="password">
        </div>
        <div class="submitButtonHolder">
            <input type="image" name="submit" value="Submit" src="./images/submit.png" class="button">
        </div>
    </form>
    <h2>Login info**</h2><p>* required<br />** use google login data</p>
</div>

 -->
