
<?php  echo $this->partial("partials/header.phtml", array('msg' => "edit event...",'username' => $this->username,));
?> 
<?php 
    echo $this->partial("partials/nav.phtml");
 ?>
<div class="contentHolder" >
    
        
    <form action="/home/edit-event-details" name="form" method="POST" id="form"> 
            <div class="textFieldHolder">
                <span>title</span><br>
                <input type="text" value="<?php echo $this->event['title']; ?>" style="width: 440px;" name="title">
            </div>
            <div class="textFieldHolder">
                <span>when</span><br>
                <input style=" width: 92px;" type="text" value="<?php echo $this->event['when'][0]['start']; ?>" id="startDate" name="startDate">
                
                <input style=" width: 50px; <?php if ($this->event['when'][0]['allDay'] == true) echo " display:none; "; ?>" maxlength="5" type="text" value="<?php if ($this->event['when'][0]['startTime'] != null) echo $this->event['when'][0]['startTime']; else echo date('H:i'); ?>" id="startTime" name="startTime">
                
                
                <span style=" margin-left: 5px;" > to 
                   <input style=" width: 92px; margin-left: 5px;" type="text" value="<?php echo $this->event['when'][0]['end']; ?>" id="endDate" name="endDate">
                   <input style=" width: 50px; <?php if ($this->event['when'][0]['allDay'] == true) echo " display:none; "; ?>" maxlength="5" type="text" value="<?php if ($this->event['when'][0]['endTime'] != null) echo $this->event['when'][0]['endTime']; else echo date('H:i'); ?>" id="endTime" name="endTime">
                   &nbsp;&nbsp;&nbsp;
                   <input type="checkbox" value="1" name="allday" id="allday" <?php if ($this->event['when'][0]['allDay'] == true) echo ' checked="checked" ' ?> /><label for="allday">all day</label>
                </span>
            </div>
            <div class="textFieldHolder">
                <span>where</span><br>
                <input type="text" value="<?php 
                    foreach ($this->event['where'] as $where){
                        if($where['location'] != null || $where['location'] != '') echo $where['location'] . " ";
                    }
                        
                 ?>" name="where">
            </div>
            <div class="textFieldHolder">
                <span>description</span><br>
                <textarea name="desc"><?php echo $this->event['desc']; ?></textarea>
            </div>
            
            <div class="reminderRow textFieldHolder" >
                <span >Reminder</span>
                
                <?php 
                $i = 0;
                if ($this->event['when'][0]['reminders'] != null)
                    foreach ($this->event['when'][0]['reminders'] as $key => $reminder) {
                            $i = $key+1;
                    ?>
                    <div id="<?php echo $i; ?>Reminder" style="margin-top: 5px;">
                        <br style="clear: both;" />
                        <div id="<?php echo $i; ?>radio" style="float: left; margin-top: 9px;">
                            <input <?php if ($reminder['method'] == 'email') echo ' checked="checked" '; ?> type="radio" id="<?php echo $i; ?>radio1" name="<?php echo $i; ?>reminderType" value="email" /><label for="<?php echo $i; ?>radio1">email</label>
                            <input <?php if ($reminder['method'] == 'sms') echo ' checked="checked" '; ?> type="radio" id="<?php echo $i; ?>radio2" name="<?php echo $i; ?>reminderType" value="sms" /><label for="<?php echo $i; ?>radio2">sms</label>
                            <input <?php if ($reminder['method'] == 'alert') echo ' checked="checked" '; ?> type="radio" id="<?php echo $i; ?>radio3" name="<?php echo $i; ?>reminderType" value="alert" /><label for="<?php echo $i; ?>radio3">alert</label>
                        </div>
                        <?php if  ($reminder['minutes']%1440 == 0){
                                  $timeForRem = $reminder['minutes']/1440;
                                  $remUnit = 'd';
                               }else if ($reminder['minutes']%60 == 0){ 
                                   $timeForRem = $reminder['minutes']/60;
                                   $remUnit = 'h';
                                }else {
                                    $timeForRem = $reminder['minutes'];
                                    $remUnit = 'm';
                                }
                        ?>
                        <input type="text"  value="<?php echo $timeForRem; ?>" name="<?php echo $i; ?>remCount" style="float: left;">
                        <div id="<?php echo $i; ?>radioUnit" style="float: left; margin-left: 5px;  margin-top: 9px;">
                            <input type="radio" id="<?php echo $i; ?>radioUnit1" name="<?php echo $i; ?>reminderUnit" value="min" <?php if ($remUnit == 'm') echo ' checked="checked" '; ?> /><label for="<?php echo $i; ?>radioUnit1">min</label>
                            <input type="radio" id="<?php echo $i; ?>radioUnit2" name="<?php echo $i; ?>reminderUnit" value="h" <?php if ($remUnit == 'h') echo ' checked="checked" '; ?>  /><label for="<?php echo $i; ?>radioUnit2">h</label>
                            <input type="radio" id="<?php echo $i; ?>radioUnit3" name="<?php echo $i; ?>reminderUnit" value="days" <?php if ($remUnit == 'd') echo ' checked="checked" '; ?>  /><label for="<?php echo $i; ?>radioUnit3">days</label>
                        </div>
                        <button onclick="removeRow(<?php echo $i; ?>);"  style="margin-top: 9px; margin-left: 20px;" id="<?php echo $i; ?>removeRem">Remove reminder</button>
                    </div>
                <?php } if ($i == 0) echo '<span id="noRemSet"><br /><em>No reminders set!</em></span>'; ?>
                
            </div>
            <br style="clear: both;" />
            <button  style="margin-left: 265px; margin-top: 15px;" id="addRem">Add new remider</button>
            <br style="clear: both;" />
            <input type="hidden" id="numOfRem" value="<?php echo count($this->event['when'][0]['reminders']); ?>" name="numOfRem" />
            <input type="hidden" id="eventId" value="<?php echo $this->eventId; ?>" name="eventId" />
            <button style="margin-left: 10px; margin-top: 15px; width: 295px;" id="cancel" >Cancel changes</button>
            <input style="margin-left: 10px; margin-top: 15px; width: 295px;" type="submit" value="Save changes"/>
            
            <br />
    </form>
  </div> 
  <script type="text/javascript" src="/js/main.js" ></script>
    <script type="text/javascript">

    $(function() {
    	
        var num = $("#numOfRem").val();

        $("input:submit").button();

        <?php if ($this->event['when'][0]['reminders'] != null)
                foreach ($this->event['when'][0]['reminders'] as $key => $reminder) {
            $i = $key+1;
                    ?>
            $("#<?php echo $i; ?>radio").buttonset();
            $("#<?php echo $i; ?>radioUnit").buttonset();
            $("#<?php echo $i; ?>removeRem").button({
                icons: {
                    primary: 'ui-icon-trash'
                },
                text: false
            });
        <?php }?>

        $("#addRem").button({
            icons: {
                primary: 'ui-icon-plus'
            },
            text: true
        }).click(function(){
            $('#noRemSet').remove();
            
            num = parseInt(num) + 1;
            num1 = parseInt($("#numOfRem").val());

            if (num1 != 5){
                var html = 
                "<div id=\""+num+"Reminder\" style=\"margin-top: 5px;\">" +
                "<br style=\"clear: both;\" />"+
                "<div id=\""+num+"radio\" style=\"float: left; margin-top: 9px;\">" +
                    "<input type=\"radio\" id=\""+num+"radio1\" name=\""+num+"reminderType\" value=\"email\" checked=\"checked\"/><label for=\""+num+"radio1\">email</label>" +
                    "<input type=\"radio\" id=\""+num+"radio2\" name=\""+num+"reminderType\" value=\"sms\"  /><label for=\""+num+"radio2\">sms</label>" +
                    "<input type=\"radio\" id=\""+num+"radio3\" name=\""+num+"reminderType\" value=\"alert\"  /><label for=\""+num+"radio3\">alert</label>" +
                "</div>" + 
                "<input type=\"text\"  value=\"3\" name=\""+num+"remCount\" style=\"float: left;\">" +
                "<div id=\""+num+"radioUnit\" style=\"float: left; margin-left: 5px; margin-top: 9px;\">" + 
                    "<input type=\"radio\" id=\""+num+"radioUnit1\" name=\""+num+"reminderUnit\" value=\"min\" /><label for=\""+num+"radioUnit1\">min</label>" + 
                    "<input type=\"radio\" id=\""+num+"radioUnit2\" name=\""+num+"reminderUnit\" value=\"h\" checked=\"checked\" /><label for=\""+num+"radioUnit2\">h</label>" + 
                    "<input type=\"radio\" id=\""+num+"radioUnit3\" name=\""+num+"reminderUnit\" value=\"days\" /><label for=\""+num+"radioUnit3\">days</label>" + 
                "</div>" + 
                "<button onclick=\"removeRow("+num+")\" style=\"margin-top: 9px; margin-left: 20px;\" id=\""+num+"removeRem\">Remove reminder<\/button>" + 
            "</div>";
                
                $('.reminderRow').append(html);
                $("#"+num+"radio").buttonset();
                
                $("#"+num+"radioUnit").buttonset();
    
                $("#"+num+"removeRem").button({
                    icons: {
                        primary: 'ui-icon-trash'
                    },
                    text: false
                });
                
                $("#numOfRem").val(num1 + 1);
            }else alert("Maximum number of reminders reached!");
            
            return false;
        });
    });

    function removeRow(id){
        $("#"+id+"Reminder").remove();
         num = $("#numOfRem").val();
         num = num - 1;
         $("#numOfRem").val(num);
    
         return false;
    }
</script>


<?php 
    echo $this->partial("partials/nav.phtml");
 ?>