<div id="header" class="contentHolder">
    
    <div class="left">
        <h1>You must first <a href="<?php echo $this->loginUrl; ?>">login</a> to see this page.</h1>
    </div>
    <div class="right">
        <img alt="logo" src="/images/logo-header.png">
        <div id="details">
            <h3>Janjić Miloš</h3>
            <p id="abbrev">i.<br>m.</p>
            <p>11640<br>dr Vidaković Milan</p>
        </div>
    </div>
</div>